<?php

return [
    'email_settings' => [
        'key' => 'email_settings',
        'label' => 'تنظیمات ایمیل',
        'description' => 'پیکربندی SMTP، Sendmail و اطلاعات فرستنده برای ارسال ایمیل از طریق صف',
        'icon' => 'email',
        'permission' => 'communication.view',
        'category' => 'communication',
    ],
    'sms_settings' => [
        'key' => 'sms_settings',
        'label' => 'تنظیمات پیامک',
        'description' => 'پیکربندی پنل ملی‌پیامک (MeliPayamak) برای ارسال OTP و اعلان‌ها از طریق صف',
        'icon' => 'sms',
        'permission' => 'communication.view',
        'category' => 'communication',
    ],
    'contact' => [
        'key' => 'contact',
        'label' => 'ماژول تماس با ما',
        'description' => 'مدیریت پیام‌های دریافتی و تنظیمات اطلاعات تماس',
        'icon' => 'contact_support',
        'permission' => 'contact.view',
        'category' => 'communication',
    ],
    'affiliate' => [
        'key' => 'affiliate',
        'label' => 'سیستم افیلیت',
        'description' => 'تنظیمات لینک‌سازی و رهگیری افیلیت',
        'icon' => 'link',
        'permission' => 'affiliate.view',
        'category' => 'communication',
    ],
    'file_manager' => [
        'key' => 'file_manager',
        'label' => 'مدیریت فایل‌ها',
        'description' => 'مدیریت فایل‌ها در صفحه اختصاصی فایل منیجر',
        'icon' => 'folder',
        'permission' => 'file_manager.view',
        'category' => 'data',
    ],
    'home_items_management' => [
        'key' => 'home_items_management',
        'label' => 'مدیریت آیتم‌های صفحه اصلی',
        'description' => 'مدیریت یکپارچه اسلایدرها، بنرها و دسته‌بندی‌های صفحه اصلی',
        'icon' => 'home_repair_service',
        'permission' => 'home_items.view',
        'category' => 'content',
    ],
    'email_templates' => [
        'key' => 'email_templates',
        'label' => 'تمپلیت ایمیل‌ها',
        'description' => 'مدیریت تمپلیت، هدر/فوتر، پیش‌نمایش و متغیرها',
        'icon' => 'drafts',
        'permission' => 'email_templates.view',
        'category' => 'communication',
    ],
    'queues' => [
        'key' => 'queues',
        'label' => 'مدیریت صف‌ها',
        'description' => 'حالت پردازش، توکن Cron و گزارش اجراها',
        'icon' => 'queue',
        'permission' => 'queues.view',
        'category' => 'technical',
    ],
    'comments' => [
        'key' => 'comments',
        'label' => 'ماژول نظرات',
        'description' => 'مدیریت نظرات، گزارش‌گیری و تنظیمات ارسال نظر',
        'icon' => 'forum',
        'permission' => 'comments.view',
        'category' => 'content',
    ],
    'tickets' => [
        'key' => 'tickets',
        'label' => 'ماژول تیکت',
        'description' => 'مدیریت تیکت‌ها، دسته‌بندی‌ها و تنظیمات ارسال تیکت',
        'icon' => 'confirmation_number',
        'permission' => 'tickets.view',
        'category' => 'content',
    ],
    'faq' => [
        'key' => 'faq',
        'label' => 'ماژول سوالات متداول',
        'description' => 'مدیریت سوالات متداول سایت و نمایش در صفحه FAQ',
        'icon' => 'quiz',
        'permission' => 'faq.view',
        'category' => 'content',
    ],
    'geoip' => [
        'key' => 'geoip',
        'label' => 'بروزرسانی GeoIP',
        'description' => 'مدیریت دیتابیس‌های مکان‌دهی IP و گزارش بروزرسانی‌ها',
        'icon' => 'language',
        'permission' => 'geoip.view',
        'category' => 'technical',
    ],
    'robots' => [
        'key' => 'robots',
        'label' => 'فایل Robots.txt',
        'description' => 'ویرایش و تست فایل robots.txt برای مدیریت دسترسی ربات‌ها',
        'icon' => 'settings_suggest',
        'permission' => 'robots.view',
        'category' => 'technical',
    ],
    'search' => [
        'key' => 'search',
        'label' => 'جستجوی هوشمند',
        'description' => 'تنظیمات جستجوی سریع در کل سیستم (ماژول‌ها، کاربران، محصولات)',
        'icon' => 'search',
        'permission' => 'search.view',
        'category' => 'technical',
    ],
    'megamenu' => [
        'key' => 'megamenu',
        'label' => 'مدیریت مگا منو',
        'description' => 'مدیریت ویژوال آیتم‌های مگا منو با قابلیت درگ اند دراپ',
        'icon' => 'menu',
        'permission' => 'megamenu.view',
        'category' => 'content',
    ],
    'error_pages' => [
        'key' => 'error_pages',
        'label' => 'مدیریت صفحات خطا',
        'description' => 'مدیریت لینک‌های کمکی و آیکون‌های نمایش داده شده در صفحات خطا',
        'icon' => 'report_problem',
        'permission' => 'error_pages.view',
        'category' => 'content',
    ],
    'cache_management' => [
        'key' => 'cache_management',
        'label' => 'مدیریت کش',
        'description' => 'تنظیمات هدرهای کش وب‌سرویس‌ها و بهینه‌سازی وب‌سرور',
        'icon' => 'bolt',
        'permission' => 'cache_management.view',
        'category' => 'technical',
    ],
    'object_cache' => [
        'key' => 'object_cache',
        'label' => 'مدیریت Object Cache',
        'description' => 'تنظیمات درایور، پیشوند، تست اتصال، پاکسازی و مرور آیتم‌های کش لاراول',
        'icon' => 'memory',
        'permission' => 'object_cache.view',
        'category' => 'technical',
    ],
    'visitor_intelligence' => [
        'key' => 'visitor_intelligence',
        'label' => 'هوشمندی بازدیدکنندگان',
        'description' => 'مدیریت الگوهای تشخیص ربات، خزنده‌ها و ASNهای معتبر',
        'icon' => 'psychology',
        'permission' => 'geoip.full',
        'category' => 'technical',
    ],
    'artisan_commands' => [
        'key' => 'artisan_commands',
        'label' => 'دستورات Artisan',
        'description' => 'اجرای دستورات کاربردی Artisan مانند پاکسازی کش، اجرای migration و ...',
        'icon' => 'terminal',
        'permission' => 'dashboard.view',
        'category' => 'technical',
    ],
    'categories' => [
        'key' => 'categories',
        'label' => 'مدیریت دسته‌بندی‌ها',
        'description' => 'مدیریت درخت دسته‌بندی محصولات و نگاشت هوشمند بین فروشگاه‌ها',
        'icon' => 'category',
        'permission' => 'dashboard.view',
        'category' => 'data',
    ],
    'sitemap' => [
        'key' => 'sitemap',
        'label' => 'مدیریت سایت مپ',
        'description' => 'تولید خودکار sitemap.xml با پشتیبانی از ایندکس چندبخشی، فشرده‌سازی gzip و پردازش افزایشی',
        'icon' => 'map',
        'permission' => 'sitemap.view',
        'category' => 'technical',
    ],
    'indexnow' => [
        'key' => 'indexnow',
        'label' => 'ایندکس‌سازی (IndexNow)',
        'description' => 'ارسال خودکار محصولات به بینگ و یاندکس با برنامه‌ریزی ساعتی و کنترل نرخ',
        'icon' => 'publish',
        'permission' => 'indexnow.view',
        'category' => 'technical',
    ],
];
